name: navicat-keygen builds
on: workflow_dispatch

jobs:
  navicat-keygen-x86:
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      shell: pwsh
      run: |
        pushd .
        cd ${env:VCPKG_INSTALLATION_ROOT}
        git pull
        vcpkg install unicorn:x86-windows-static
        vcpkg install fmt:x86-windows-static
        vcpkg install rapidjson:x86-windows-static
        vcpkg install keystone:x86-windows-static
        vcpkg install capstone:x86-windows-static
        git switch -c openssl-1.1.1 89295c9fe22e97ca9e380a6c771ccf2ff09dca95
        bootstrap-vcpkg.bat
        wget https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst -P ${env:VCPKG_INSTALLATION_ROOT}\downloads
        vcpkg install openssl:x86-windows-static
        popd

    - name: Clone source
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Clone
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        git clone https://notabug.org/doublesine/navicat-keygen
        cd navicat-keygen
        git checkout windows-coool

    - name: Build project
      run: |
        vcpkg integrate install
        msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x86

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: navicat-keygen-x86.zip
        path: bin/x86-Release/*.exe

  navicat-keygen-x64:
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
        pushd .
        cd ${env:VCPKG_INSTALLATION_ROOT}
        git pull
        vcpkg install unicorn:x64-windows-static
        vcpkg install fmt:x64-windows-static
        vcpkg install rapidjson:x64-windows-static
        vcpkg install keystone:x64-windows-static
        vcpkg install capstone:x64-windows-static
        git switch -c openssl-1.1.1 89295c9fe22e97ca9e380a6c771ccf2ff09dca95
        bootstrap-vcpkg.bat
        vcpkg install openssl:x64-windows-static
        popd

    - name: Clone source
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Clone
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        git clone https://notabug.org/doublesine/navicat-keygen
        cd navicat-keygen
        git checkout windows-coool

    - name: Build project
      run: |
        vcpkg integrate install
        msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: navicat-keygen-x64.zip
        path: bin/x64-Release/*.exe
